In [1]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

In [14]:
review_distribution = pd.read_json('../full_dataset/visit_distribution.json')
review_distribution['merge_token'] = review_distribution.apply(lambda x: x['authority_id'] + ',' + str(x['authority_stars']) + ',' + str(x['distance']), axis = 1)

In [ ]:
d_before = DataFrame(review_distribution.loc[review_distribution['time_distribution'] == 0])
d_before.columns=['count_before', 'authority_id', 'authority_stars', 'distance', 'time_distribution', 'merge_token']
d_after = DataFrame(review_distribution.loc[review_distribution['time_distribution'] == 1][['merge_token', '0']])
d_after.columns = ['merge_token', 'count_after']

In [20]:
factor = pd.merge(d_before, d_after, on = 'merge_token')[['authority_id', 'authority_stars', 'distance', 'count_before', 'count_after']]
factor['factor'] = aggregate_result.apply(lambda x: x['count_after'] / x['count_before'], axis = 1)
factor.head()

,authority_id,authority_stars,distance,count_before,count_after,factor
0,-2RVxn8RRN3j9bOiqGkjug,5,4,4,4,1.000000
1,-4AMRN-7RtozD9s8ZsH04g,4,3,56,69,1.232143
2,0bNXP9quoJEgyVZu9ipGgQ,4,3,54,115,2.129630
3,NjOYSgr2LNMoSPi4e140Ig,3,5,4,12,3.000000
4,NjOYSgr2LNMoSPi4e140Ig,4,5,1,7,7.000000

In [31]:
aggregate_result = factor[['authority_stars', 'distance', 'factor']].groupby(['authority_stars', 'distance'], as_index = False)['factor'].agg({'size': np.size, 'factor': np.mean, 'sigma': np.std })
aggregate_result.loc[aggregate_result['size'] > 3]

    authority_stars  distance  size      sigma     factor
0                 1         2    21   1.702245   1.593538
1                 1         3    31   3.148726   2.548335
2                 1         4    29  14.064348   7.257135
3                 1         5    19   6.421885   5.440852
5                 2         2    51   3.023513   2.079316
6                 2         3    47  12.466931   5.819026
7                 2         4    44   9.946139   5.926495
8                 2         5    23   7.978910   4.748419
9                 3         1     9   0.486706   0.925926
10                3         2    78   2.464113   1.657321
11                3         3    74  29.923825   9.914123
12                3         4    70   7.299004   6.099171
13                3         5    47  10.091151   7.041043
14                4         1     7   0.749559   1.107143
15                4         2    97   4.110338   2.740103
16                4         3    96  31.980961  13.296396
17                4         4    83  19.967864  10.468671
18                4         5    64   9.646900   6.403126
20                5         2    45   2.472683   1.817914
21                5         3    45  44.456289  12.072681
22                5         4    41  41.552748  14.054402
23                5         5    25   4.921034   4.770495